### PR TITLE
Testing

### LINKED ISSUE #25: Testing
What I want to build:
- Tests should not add any overhead for none-testing binaries
- Tests should show exactly why they fail if they fail
- Testing code should not clutter source code files but testing code can be at the bottom of source code files
- Testing should be easy to do just from the command line

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #25

### CODE REVIEW

File: src/testing/tassert.h [hunk 1]
```diff
@@ -0,0 +1,5 @@
+#include <assert.h>
+
+#define tassert(e) ((void)((e) ? 0 : __assert(#e, __FILE__, __LINE__)))
```
Comment (adamhutchings) [inline src/testing/tassert.h:3]: I'm actually not familiar with how this would work -- does this expand out to always be `src/testing/tassert.h`, line `3` or does it work as expected?

**Review by adamhutchings — APPROVED** [review]
Good as long as the question I have is answered

File: src/testing/tassert.h (hunk 1 above)
Comment (JakeRoggenbuck) [reply src/testing/tassert.h:3]: Yup, it totally works. I just used the definition of assert from assert.h (shared on stackoverflow) and removed the abort().

Here is where I got the idea to use assert redefinition and where I got the definition
https://stackoverflow.com/a/270797/10621852
